version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/perimeter-server
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstallHook.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: root
  #AfterInstall:
  #  - location: scripts/AfterInstallHook.sh
  #    timeout: 300
